In [1]:
import requests

In [5]:
import pandas as pd

df = pd.read_parquet('../nyc_taxi_data/green_tripdata_2025-01.parquet')
df.head().T

,0,1,2,3,4
VendorID,2,2,2,2,2
lpep_pickup_datetime,2025-01-01 00:03:01,2025-01-01 00:19:59,2025-01-01 00:05:29,2025-01-01 00:52:24,2025-01-01 00:25:05
lpep_dropoff_datetime,2025-01-01 00:17:12,2025-01-01 00:25:52,2025-01-01 00:07:21,2025-01-01 01:07:52,2025-01-01 01:01:10
store_and_fwd_flag,N,N,N,N,N
RatecodeID,1.0,1.0,5.0,1.0,1.0
PULocationID,75,166,171,74,66
DOLocationID,235,75,73,223,158
passenger_count,1.0,1.0,1.0,1.0,1.0
trip_distance,5.93,1.32,0.41,4.12,4.71
fare_amount,24.7,8.6,25.55,21.2,33.8
extra,1.0,1.0,0.0,1.0,1.0
mta_tax,0.5,0.5,0.0,0.5,0.5
tip_amount,6.8,0.0,0.0,6.13,7.81
tolls_amount,0.0,0.0,0.0,6.94,0.0
ehail_fee,NaN,NaN,NaN,NaN,NaN
improvement_surcharge,1.0,1.0,1.0,1.0,1.0
total_amount,34.0,11.1,26.55,36.77,46.86
payment_type,1.0,2.0,2.0,1.0,1.0
trip_type,1.0,1.0,2.0,1.0,1.0
congestion_surcharge,0.0,0.0,0.0,0.0,2.75
cbd_congestion_fee,0.0,0.0,0.0,0.0,0.0

In [ ]:
import pyarrow.parquet as pq
import pyarrow
import pyarrowfs_adlgen2
from dotenv import load_dotenv
import os

load_dotenv()


ADLS_NAME = os.getenv(ADLS_NAME)
ADLS_KEY =  os.getenv(ADLS_KEY)
directory = "sources"  # ou ajuste conforme necessário

handler = pyarrowfs_adlgen2.AccountHandler.from_account_name(ADLS_NAME, ADLS_KEY)
fs = pyarrow.fs.PyFileSystem(handler)

# Lista todos os blobs/parquet no container 'taxi'
blobs = container_client.list_blobs(name_starts_with='source/')
total_rows = 0

for blob in blobs:
    if blob.name.endswith('.parquet'):
        pf = pq.ParquetFile(f"taxi/{blob.name}", filesystem=fs)
        total_rows += pf.metadata.num_rows

print(f"Total de linhas em todos os arquivos parquet: {total_rows}")

Total de linhas em todos os arquivos parquet: 862600722

In [56]:
total_mem = 0

# Recrie o iterador de blobs
blobs = container_client.list_blobs(name_starts_with='source/')

for blob in blobs:
    # print(blob.name)
    total_mem += blob.size

print(f"Total de memória em todos os arquivos parquet: {total_mem/(1024)**3:2f} GBs")

Total de memória em todos os arquivos parquet: 31.608605 GBs